### PR TITLE
Task Estimation related content is added.

### PR DESCRIPTION
**Pull request by Yemaneberhan-Lemma**

### CODE REVIEW

**Review by hussainweb — CHANGES_REQUESTED** [review]
@Yemaneberhan-Lemma, the second paragraph is very similar to the first one. Besides, how is this content helping? This reads like the Wikipedia definition of estimations. What does it tell us about how we work?

**Comment by Yemaneberhan-Lemma** [comment]
> @Yemaneberhan-Lemma, the second paragraph is very similar to the first one. Besides, how is this content helping? This reads like the Wikipedia definition of estimations. What does it tell us about how we work?

@hussainweb: I will make changes to the content so that it can show how we work.

**Comment by hussainweb** [comment]
@Kalaiselvan88 @swarad07, I would like your reviews before I merge this.

**Review by hussainweb — APPROVED** [review]

**Comment by Yemaneberhan-Lemma** [comment]
@Kalaiselvan88 & @hussainweb : Please review the changes I made. Thanks.

**Comment by hussainweb** [comment]
@Kalaiselvan88, might I suggest that even if all the details are not yet in, and if the current changes make sense even if incomplete, let's merge it? We can reiterate and add more content in subsequent PRs.

**Comment by hussainweb** [comment]
Certainly, @Kalaiselvan88. Some of your suggestions work better as issues and we will be able to track them as well. Once all the issues are done, we can clear up the content on Confluence. At the same time, we don't have one large PR that is difficult to review.

The only comment I'd rather fix in this PR is the one here: https://github.com/axelerant/engg-handbook/pull/165#discussion_r1647757443. As I understand it, only a link is missing and can be fixed immediately.

**Comment by Yemaneberhan-Lemma** [comment]
@Kalaiselvan88 @hussainweb: I'll update the link issue and major points that are missing within an hour. However, I tried to make the content as compact as possible and avoid redundancy.
Thanks.

**Comment by hussainweb** [comment]
@Kalaiselvan88, since the only comment we agreed upon to be fixed in this PR has been fixed, I'm merging it. I'm doing it so that we can focus on the next additions incrementally. Please raise new issues for something that seems wrong in this PR.

**Pull request merged**
