### PR TITLE
Content about Quality as Teamwork

### PR DESCRIPTION
**Pull request by Yemaneberhan-Lemma**

### CODE REVIEW

**Comment by hussainweb** [comment]
@Yemaneberhan-Lemma, what is the source of this content? Why have a separate page for this when we have pages on automated testing and Quality Engineering?

**Comment by Yemaneberhan-Lemma** [comment]
> @Yemaneberhan-Lemma, what is the source of this content? Why have a separate page for this when we have pages on automated testing and Quality Engineering?

The source is content recommendations from @Kalaiselvan88 in this [spreadsheet](https://docs.google.com/spreadsheets/d/1XQJd5QfUGT-cOWwqiuQIb8U5rGSDPsIxGL-tB8yHvq0/edit?gid=0#gid=0).

**Comment by hussainweb** [comment]
Thanks, @Yemaneberhan-Lemma. Please try to merge this with other content. It is not in the same tone of voice as the rest of the pages and seems weirdly placed in the content. Look at the nearby pages: there is no logical order.

**Comment by Yemaneberhan-Lemma** [comment]
> Thanks, @Yemaneberhan-Lemma. Please try to merge this with other content. It is not in the same tone of voice as the rest of the pages and seems weirdly placed in the content. Look at the nearby pages: there is no logical order.

@hussainweb: I made changes and moved it to Coding Standards and Principles page.

**Review by hussainweb — APPROVED** [review]
@shwetaneelsharma, I'll merge this for now but I'd love your review to rephrase or otherwise edit this content. Thank you!

**Pull request merged**
