### PR TITLE
Logo click takes you to 404 fix.

### PR DESCRIPTION
**Pull request by axelabhay**
Possible solution to fix landing to 404 page when logo is clicked.

### CODE REVIEW

**Comment by axelabhay** [comment]
Hi @hussainweb @Yemaneberhan-Lemma 
This could be a possible solution, if this does not work then we need to try with hardcoding it with `<a href="{{ .Site.BaseURL }}"engg-handbook>`

**Review by hussainweb — CHANGES_REQUESTED** [review]
This doesn't work. It returns an empty string because it is empty in the configuration (and we can't change that). So, it looks like it is working from the home page but not from any of the inner pages.

From the [documentation](https://gohugo.io/methods/site/baseurl/):

> There is almost never a good reason to use this method in your templates. Its usage tends to be fragile due to misconfiguration.
> 
> Use the [absURL](https://gohugo.io/functions/urls/absurl/), [absLangURL](https://gohugo.io/functions/urls/abslangurl/), [relURL](https://gohugo.io/functions/urls/relurl/), or [relLangURL](https://gohugo.io/functions/urls/rellangurl/) functions instead.

**Comment by axelabhay** [comment]
> This doesn't work. It returns an empty string because it is empty in the configuration (and we can't change that). So, it looks like it is working from the home page but not from any of the inner pages.
> 
> From the [documentation](https://gohugo.io/methods/site/baseurl/):
> 
> > There is almost never a good reason to use this method in your templates. Its usage tends to be fragile due to misconfiguration.
> > Use the [absURL](https://gohugo.io/functions/urls/absurl/), [absLangURL](https://gohugo.io/functions/urls/abslangurl/), [relURL](https://gohugo.io/functions/urls/relurl/), or [relLangURL](https://gohugo.io/functions/urls/rellangurl/) functions instead.

Noted. Thanks @hussainweb for these details. I will re-check and update the PR.

**Comment by axelabhay** [comment]
Hi @hussainweb I have just update the PR considering the usage of relURL for "src" attribute values in our existing HTML templates. Please review.

**Pull request merged**
