### PR TITLE
Content about writing API for versatility as principle

### PR DESCRIPTION
**Pull request by Yemaneberhan-Lemma**

### CODE REVIEW

**Comment by axelabhay** [comment]
Hi @Yemaneberhan-Lemma, to me the `Future proofing` & `Versatile API` sections seems sharing similar ideas. Please adjust the contents if you see applicable.

**Comment by Yemaneberhan-Lemma** [comment]
> Hi @Yemaneberhan-Lemma, to me the `Future proofing` & `Versatile API` sections seems sharing similar ideas. Please adjust the contents if you see applicable.

@axelabhay, The main reason the last paragraph appears redundant is because I was trying to mention all the key characteristics of a versatile API. Though, I made changes to the paragraph.

**Comment by hussainweb** [comment]
I reflected on this and am of the opinion that this is too specific to be a principle. I do get the intent on how the word "API" can be applied here but it is still not generic enough.

If I were to rephrase this in a generic way, it would be "Separation of concerns". And I think that is also not applicable as a principle. I mean, it is hardly useful to say "Separate your concerns". I think this is more of a contextual topic under "Common areas of concern".

**Comment by Yemaneberhan-Lemma** [comment]
Noted

**Comment by hussainweb** [comment]
Closing this as it has been a long time. Reopen if required.

**Pull request closed without merging**
