### PR TITLE
Added content about tickets prioritization

### PR DESCRIPTION
**Pull request by Yemaneberhan-Lemma**
Source: https://learning.axelerant.com/courses/take/CDM-developer-guidelines/texts/35511248-priority-for-picking-up-the-tickets

### CODE REVIEW

**Review by hussainweb — CHANGES_REQUESTED** [review]
@Yemaneberhan-Lemma, I can't see this making sense in the "Principles" section. Can you find a relevant section in "Behaviours" or "How to be productive" and move it there?

**Comment by Yemaneberhan-Lemma** [comment]
> @Yemaneberhan-Lemma, I can't see this making sense in the "Principles" section. Can you find a relevant section in "Behaviours" or "How to be productive" and move it there?

@hussainweb: Rewrote content and moved to a new page under Being Productive.

**Comment by hussainweb** [comment]
Reading this, I would rather call it "Prioritizing Tasks". Then make the language a bit more generic. Right now, it is too specific to CDM practices.

**Review by hussainweb — CHANGES_REQUESTED** [review]
Reading this, I would rather call it "Prioritizing Tasks". Then make the language a bit more generic. Right now, it is too specific to CDM practices.

**Comment by Yemaneberhan-Lemma** [comment]
> Reading this, I would rather call it "Prioritizing Tasks". Then make the language a bit more generic. Right now, it is too specific to CDM practices.

@hussainweb: Done as per comment.

**Comment by hussainweb** [comment]
Thanks! Will wait for @Kalaiselvan88's review before merging.

**Review by Kalaiselvan88 — APPROVED** [review]

**Comment by Kalaiselvan88** [comment]
Thanks this PR can be merged

**Review by hussainweb — APPROVED** [review]

**Pull request merged**
