### PR TITLE
Add page on debugging

### PR DESCRIPTION
**Pull request by binnyaxel**
HI @panshulK 

I have included pragmatic principles as requested into the previous changes I made.

### CODE REVIEW

**Comment by panshulK** [comment]
LGTM!
Thanks @binnyaxel 👍🏼

**Comment by hussainweb** [comment]
@binnyaxel, can you please look at the failures? These should be simple fixes.

**Comment by hussainweb** [comment]
@binnyaxel, I just noticed that this is replacing #63. Is that the intention? If so, can you please close that PR in favour of this one.

**Comment by binnyaxel** [comment]
> @binnyaxel, can you please look at the failures? These should be simple fixes.

I have addressed this. Please do the needful.

> @binnyaxel, I just noticed that this is replacing #63. Is that the intention? If so, can you please close that PR in favour of this one.

I have done this as well.  @hussainweb

**Comment by hussainweb** [comment]
@binnyaxel, sorry it took so long to get back to this. I ran the workflow and there are still some errors. Can you please fix them? If you don’t find the time, please let me know.

**Comment by binnyaxel** [comment]
@hussainweb I have addressed the errors. Please check now.

**Pull request merged**
